name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once every day at midnight
  workflow_dispatch:      # lets you trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: SonuKumarPaswan
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
